### ISSUE TITLE
move new proj to master

### ISSUE THREAD

**Issue by wolfbiter** [linxmix/linx#353]

**Comment by ahdinosaur** [comment]
:+1:, but can you archive the current master in another branch, say `oldlinx2`? :tractor:

**Comment by wolfbiter** [comment]
of course haha. i wouldn't throw that work away :P

**Comment by ahdinosaur** [comment]
hehe cool.

**Comment by wolfbiter** [comment]
@ahdinosaur note new branch, `origin/deprecated/linx-backbone-react`
