### ISSUE TITLE
proxy server for API requests

### ISSUE THREAD

**Issue by wolfbiter** [linxmix/linx#390]
don't have a clear plan for this with ember and firebase

needs caching, in particular for soundcloud stream requests

**Comment by wolfbiter** [comment]
@ahdinosaur my server knowledge is very limited. do you have a simple answer for this? here's a scenario:

This endpoint does not support CORS '`https://api-v2.soundcloud.com/explore/Popular+Music?client_id=XX`
From the client, i want to be able to call something like `proxy('get', <url>)`, and have that route through the proxy server.

what would `function proxy(type, url)` look like? i assume i need to run a server in a separate process

**Comment by wolfbiter** [comment]
@ahdinosaur looks like i was able to very simple accomplish the above with:

1. in `simple-http.js`
```
var express = require('express');
var request = require('request');

var app = express();
var apiServerHost = 'https://api-v2.soundcloud.com';
app.use('/', function(req, res) {
  console.log('serve: ' + req.url);
  var url = apiServerHost + req.url;
  req.pipe(request(url)).pipe(res);
});

app.listen(4004);
```
2. `node simple-http.js`

3. `ember server --port=3000 --proxy=http://localhost:4004`

i'm not cetain what's going on here - is EVERY request coming from ember proxying to 4004?

**Comment by ahdinosaur** [comment]
that's a clever `express` + `request` proxy. :smile:

back in the day we used [`cors-anywhere`](https://www.npmjs.com/package/cors-anywhere), which is built on [`http-proxy`](https://www.npmjs.com/package/http-proxy), which handled CORS proxying for us.

looking at [ember-cli#getting-started](http://www.ember-cli.com/user-guide/#getting-started),

> Use the --proxy flag to proxy all ajax requests to the given address. For example, ember server --proxy http://127.0.0.1:8080 will proxy all ajax requests to the server running at http://127.0.0.1:8080.

but it's unclear then how to keep that proxy when you deploy.

looking at [ember-cli#deployments](http://www.ember-cli.com/user-guide/#deployments), if you deploy using the buildpack (heroku or dokku), it's possible to [setup a custom nginx that handles CORS proxying](http://blog.themillhousegroup.com/2013/05/nginx-as-cors-enabled-https-proxy.html), which would be quite efficient although not do any caching. the best production quality proxy cache is [squid](www.squid-cache.org), but that's probably overkill at this time when we really just need something that works.

anyways, i'd use `cors-anywhere` as your proxy while developing, then ping me again when you're ready to deploy. is that helpful? <3

**Comment by wolfbiter** [comment]
@ahdinosaur yes got all requests working and proxying locally! wavesurfer uses its own XHR implementation so didn't piggy back off of ember's proxying - i added a hack to prepend `wavesurfer.loadStreamUrl(url)` url with the proxy.

punting on deployment sounds great to me. i'm getting closer to wanting to deploy; i can update you with progress tomorrow in our sync

**Comment by wolfbiter** [comment]
deployed 9/14
